server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:productdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: PRODUCT-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
