server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:paymentdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
